{"uid":"2170bd39ba3d3416","name":"Consultar el saldo de una cuenta existente","fullName":"Gestión de cuentas: Consultar el saldo de una cuenta existente","historyId":"f677694cd9a0b5112235be74339d3cbe","time":{"start":1732866758662,"stop":1732866758664,"duration":2},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'user'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\account_manager_steps.py\", line 37, in step_impl\n    context.balance = context.user[\"balance\"]  # Consultamos el saldo de la cuenta\n                      ^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'user'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\account_manager_steps.py\", line 37, in step_impl\n    context.balance = context.user[\"balance\"]  # Consultamos el saldo de la cuenta\n                      ^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[{"name":"Given un usuario con una cuenta registrada","time":{"start":1732866758663,"stop":1732866758663,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"When el usuario consulta el saldo de su cuenta","time":{"start":1732866758663,"stop":1732866758664,"duration":1},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'user'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\account_manager_steps.py\", line 37, in step_impl\n    context.balance = context.user[\"balance\"]  # Consultamos el saldo de la cuenta\n                      ^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0},{"name":"Then se muestra el saldo actual","time":{"start":1732866758664,"stop":1732866758664,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"attachmentStep":false,"stepsCount":3,"shouldDisplayMessage":false,"attachmentsCount":0},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Gestión de cuentas"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"2170bd39ba3d3416.json","parameterValues":[]}